stages:
  - build

build:
  variables:
    GIT_SUBMODULE_STRATEGY: none
    GIT_CLEAN_FLAGS: none
  image: 
    name: registry.softcatala.org/ciaran/openvoiceos:builder-0.0.5
    entrypoint: [""]
  stage: build
  cache:
    key: ccache
    paths:
      - ccache
      - downloads
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - logs
    expire_in: 1 week
  script:
    - bash ./gitlab-build.sh
  only:
    - catala